# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5uFZIlIY9pbFoYdw7M2bSLGViOZagAJ
"""

print("escolha a operação: ")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

escolha = input("Digite o número da operação desejada:  (1/2/3/4)")

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

if escolha == '1':

  resultado = num1 + num2
  print("o resultado da soma é: ", resultado)

elif escolha == '2':

  resultado = num1 - num2
  print("o resultado da subtração é: ", resultado)

elif escolha == '3':

  resultado = num1 * num2
  print("o resultado da multiplicação é: ", resultado)

elif escolha == '4':
   if num2 != 0:
    resultado = num1 / num2
    print("o resultado da divisão é: ", resultado)
   else:
    print("Erro: Não é possível dividir por 0! ")

else:
  print("Opção Inválida! ")